name: Build dev documentation

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: "Set up Python 3.11"
        uses: actions/setup-python@v1
        with:
          python-version: '3.11'
      - include: common_documentation-steps.yml
      - name: Switch to gh-pages branch
        run: git checkout gh-pages
      - name: Copy documentation to the dev folder of gh-pages
        run: |
          rm -rf dev/
          mkdir dev/
          cp -r docs/build/html/* dev
      - name: Commit and push dev documentation
        run: |
          git add dev/*
          git commit -m "Update dev documentation"
          git push
          