name: Build dev documentation

on:
  - push
  # push:
  #   branches:
  #     - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: "Set up Python 3.11"
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: "Install pandoc"
        run: |
          sudo apt-get install -y pandoc
      - name: Install AISee package and dependecies
        run: |
          pip install poetry
          poetry install --with docs
      - name: Build latest documentation
        run: |
          cd docs/
          make copy-examples
          make html-poetry
      - name: List directories
        run: ls
      - name: List branches
        run: git branch -a
      - name: Switch to gh-pages branch
        run: git checkout gh-pages
      - name: Check git status
        run: git status
      - name: Copy documentation to the dev folder of gh-pages
        run: |
          rm -rf dev/
          mkdir dev/
          cp -r docs/build/html/* dev
      - name: List directories
        run: ls
      - name: List directories dev
        run: ls dev
      - name: Add username and user email
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      - name: Add dev directory
        run: git add dev/*
      - name: Check git status
        run: git status
      - name: Commit
        run: git commit -m "Update dev documentation"
      - name: Push dev documentation
        run: git push
          