name: Build documentation for testing

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: "Set up Python 3.11"
        uses: actions/setup-python@v1
        with:
          python-version: '3.11'
      - name: Install sphinx and dependecies
        run: pip install sphinx==6.2.0 nbsphinx==0.9.1 sphinx-design==0.4.1 pydata-sphinx-theme==0.13.3
      - name: Install AISee package
        run: pip install .
      - name: Build latest documentation
        run: |
          cd docs/
          make copy-examples
          make html
      - uses: actions/upload-artifact@v2
        with:
          name: documentation
          path: docs/build/html
          retention-days: 30
        