name: pypi

on:
  push:
    tags:        
      - "*.*.*"

jobs:
  publish_pypi:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repo
        uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Publish to Pypi
        run: |
          echo -e "\n\n__version__ = \"$GITHUB_REF_NAME\"" >> aisee/__init__.py
          pip install poetry
          poetry version $GITHUB_REF_NAME
          poetry publish --build --username __token__ --password ${{ secrets.PYPI_API_TOKEN }}
